### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by ahmad-mn-zaza** [src-d/kmcuda#78] opened 2019-04-24 15:13 UTC
Hi,

I'm running this line: `cmake -G "Visual Studio 15 2017 Win64" -DDISABLE_R=y -DCMAKE_BUILD_TYPE=Release . && make` and I'm getting the following error:
`-- Found OpenMP_C: -openmp
-- Found OpenMP_CXX: -openmp
-- Found OpenMP: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Ahmad M.N. Zaza/kmcuda/src
make: *** No targets specified and no makefile found.  Stop.`

Is it an issue with my make.exe? or are there other parameters I need to pass?
I've actually also edited the setup.py file ad this line `check_call(("make", "-j%d" % cpu_count()))`
seems to be causing an error. It seems that there is something weird going with parameter passing. Any help would be much appreciated.

**Comment by vmarkovtsev** [comment] 2019-04-24 15:34
Sorry, but Windows is not supported. I am closing this.

Anyway, the problem here is that you generate "Visual Studio 15 2017 Win64" build files instead of makefiles. Please refer to cmake documentation for Windows.

**Closed by vmarkovtsev** 2019-04-24 15:34 UTC

**Comment by smola** [comment] 2019-08-27 10:36
Duplicate of https://github.com/src-d/kmcuda/issues/50
